apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.productService.name }}
  ports:
    - port: {{ .Values.productService.servicePort }}
      targetPort: {{ .Values.productService.containerPort }}
  type: ClusterIP
